In [39]:
import pandas as pd
import numpy as np
df = pd.read_csv('/Users/dashabalashova/1_1_5_ML_Bioinf/data/mnist.csv')

df.head()

arr = []

for n in range(0,df.shape[0]):
    arr.append([df.iloc[n,0], np.array(df.iloc[n,1:]).reshape(28,28)])

,label,0,1,2,3,4,5,6,7,8,...,774,775,776,777,778,779,780,781,782,783
0,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [83]:
from PIL import Image

def arr(png_in):
    img = Image.open(png_in).convert('RGBA')
    arr = np.array(img)
    return arr

s = []
for s1 in ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J']:
    s2 = ! ls ~/1_1_5_ML_Bioinf/data/notMNIST_small/$s1
    for s3 in s2:
        s.append('/Users/dashabalashova/1_1_5_ML_Bioinf/data/notMNIST_small/'+s1+'/'+s3)
        
M_arr=[]
for png_in in s:
    try:
        M_arr.append([arr(png_in),png_in[58:59]])
    except OSError:
        pass